// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5QvwikIdkqMEUnCuUZljBBTVDKuh6WE',
    appId: '1:922244716380:web:828a0cec83900c0b4b5399',
    messagingSenderId: '922244716380',
    projectId: 'otakuapp-8d8c6',
    authDomain: 'otakuapp-8d8c6.firebaseapp.com',
    storageBucket: 'otakuapp-8d8c6.firebasestorage.app',
    measurementId: 'G-PCZXQKTVWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbAxhFfA7fG7TkUhPY86RjN8vSTmNMGs',
    appId: '1:922244716380:android:ff205ceca1f369664b5399',
    messagingSenderId: '922244716380',
    projectId: 'otakuapp-8d8c6',
    storageBucket: 'otakuapp-8d8c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmRphUzPTlEtIWlOc1Njm0gmdoV-6ok0',
    appId: '1:922244716380:ios:0bb721c15bd6af894b5399',
    messagingSenderId: '922244716380',
    projectId: 'otakuapp-8d8c6',
    storageBucket: 'otakuapp-8d8c6.firebasestorage.app',
    iosClientId: '922244716380-ehpf2cir9o6t1aq3ia7ahfsk4d9a9juh.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmRphUzPTlEtIWlOc1Njm0gmdoV-6ok0',
    appId: '1:922244716380:ios:0bb721c15bd6af894b5399',
    messagingSenderId: '922244716380',
    projectId: 'otakuapp-8d8c6',
    storageBucket: 'otakuapp-8d8c6.firebasestorage.app',
    iosClientId: '922244716380-ehpf2cir9o6t1aq3ia7ahfsk4d9a9juh.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs5QvwikIdkqMEUnCuUZljBBTVDKuh6WE',
    appId: '1:922244716380:web:4bbf62355cfe813d4b5399',
    messagingSenderId: '922244716380',
    projectId: 'otakuapp-8d8c6',
    authDomain: 'otakuapp-8d8c6.firebaseapp.com',
    storageBucket: 'otakuapp-8d8c6.firebasestorage.app',
    measurementId: 'G-R80N2165R9',
  );
}